export interface IRoutes {
  LAYOUT: string;
  SIGNIN: string;
  SIGNUP: string;
  VERIFICATION_QUESTIONS: string;
  PREVIOUS_LOCATION: string;
  PASSWORD_DISPLAY: string;
  CHANGE_PASSWORD: string;
  EDIT_PROFILE: string;
  MY_APPLICATIONS: string;
  // DAMAGE_ASSESSMENT_DIALOG: string;
  CURRENT_LOCATION: string;
  PERSONAL_INFO: string;
  SETTINGS: string;
  FAMILY_INFO: string;
  // DAMAGE_ASSESSMENT: string;
  // DOCUMENTS: string;
  // MAP: string;
  REVIEW: string;
  SUCCESS: string;
  TRACK_STATUS: string;
  ADMIN_LOGIN: string;
  ADMIN_DASHBOARD: string;
  ADMIN_USERS: string;
  ADMIN_APPLICATIONS: string;
  ADMIN_CITIZENS: string;
  ADMIN_LOCATIONS: string;
  ADMIN_LOCATION_MAP: string;
  CITIZEN_DASHBOARD: string;
  ADMIN_BANKING: string;
  FORGOT_PASSWORD: string;
  BANK_INFORMATION: string;
}
